import { graphEdgeTypeRegistry, graphNodeTypeRegistry } from "@skill-designer/engine";

export function genericEngineCli(): string {
  const nodeKinds = JSON.stringify(graphNodeTypeRegistry.map((item) => item.kind));
  const edgeKinds = JSON.stringify(graphEdgeTypeRegistry.map((item) => item.kind));
  return [
    "#!/usr/bin/env node",
    "import { createHash } from 'node:crypto';",
    "import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';",
    "import path from 'node:path';",
    "import { fileURLToPath } from 'node:url';",
    "",
    "const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');",
    "const manifest = readJson(path.join(root, 'skill.json'), 'skill.json');",
    "const graph = readJson(path.join(root, 'graph', 'main.json'), 'graph/main.json');",
    "const packageManifest = readJson(path.join(root, 'export-manifest.json'), 'export-manifest.json');",
    "validatePackageManifest();",
    "validateGraph();",
    "const command = process.argv[2] ?? 'inspect';",
    "",
    "if (command === 'verify') {",
    "  verifyPackage();",
    "} else if (command === 'inspect') {",
    "  output({ skillId: manifest.skillId, name: manifest.name, capability: graph.capability, entry: graph.entry ?? null, nodes: graph.nodes.length, edges: graph.edges.length });",
    "} else if (command === 'transitions') {",
    "  const nodeId = process.argv[3];",
    "  if (!nodeId) usage('skill-engine.mjs transitions <nodeId> [--variables <json>]');",
    "  const variables = jsonObject(option('--variables') ?? '{}', '--variables');",
    "  output(transitions(nodeId, variables));",
    "} else if (command === 'run') {",
    "  runCommand(process.argv[3] ?? 'status');",
    "} else {",
    "  usage('skill-engine.mjs verify | inspect | transitions <nodeId> [--variables <json>] | run <start|status|next|pause|resume|stop> --state <file>');",
    "}",
    "",
    "function validatePackageManifest() {",
    "  if (!plainObject(packageManifest) || packageManifest.schemaVersion !== '1.0' || packageManifest.profile !== 'generic/1') fail('package_manifest_invalid', 'export-manifest.json 不是受支持的 generic/1 清单');",
    "  if (packageManifest.skillId !== manifest.skillId || typeof packageManifest.revisionId !== 'string' || typeof packageManifest.contentHash !== 'string') fail('package_identity_mismatch', '导出清单与 skill.json 身份不一致');",
    "  if (!Array.isArray(packageManifest.files) || packageManifest.files.length < 1) fail('package_manifest_invalid', '导出清单缺少文件列表');",
    "  const paths = new Set();",
    "  for (const file of packageManifest.files) {",
    "    if (!plainObject(file) || !safePackagePath(file.path) || paths.has(file.path)) fail('package_manifest_invalid', '导出清单包含无效或重复路径');",
    "    if (!Number.isInteger(file.size) || file.size < 0 || typeof file.sha256 !== 'string' || !/^sha256:[0-9a-f]{64}$/.test(file.sha256)) fail('package_manifest_invalid', `导出清单文件 ${file.path} 的大小或 SHA-256 无效`);",
    "    paths.add(file.path);",
    "  }",
    "  if (!paths.has('skill.json') || !paths.has('graph/main.json') || !paths.has('engine/skill-engine.mjs') || !paths.has('engine/README.md')) fail('package_manifest_invalid', '导出清单缺少通用包必需文件');",
    "}",
    "",
    "function verifyPackage() {",
    "  const mismatches = []; let totalBytes = 0;",
    "  for (const file of packageManifest.files) {",
    "    const target = packageFile(file.path); let bytes;",
    "    try { bytes = readFileSync(target); } catch (error) { mismatches.push({ path: file.path, code: 'missing', message: error.code === 'ENOENT' ? '文件不存在' : error.message }); continue; }",
    "    totalBytes += bytes.length;",
    "    const actualHash = `sha256:${createHash('sha256').update(bytes).digest('hex')}`;",
    "    if (bytes.length !== file.size || actualHash !== file.sha256) mismatches.push({ path: file.path, code: 'mismatch', expectedSize: file.size, actualSize: bytes.length, expectedSha256: file.sha256, actualSha256: actualHash });",
    "  }",
    "  if (mismatches.length) fail('package_integrity_failed', `${mismatches.length} 个导出文件缺失或内容不一致`, { checkedFiles: packageManifest.files.length, mismatches });",
    "  output({ schemaVersion: '1.0', profile: packageManifest.profile, skillId: packageManifest.skillId, revisionId: packageManifest.revisionId, contentHash: packageManifest.contentHash, valid: true, checkedFiles: packageManifest.files.length, totalBytes });",
    "}",
    "",
    "function safePackagePath(value) { return typeof value === 'string' && value.length > 0 && value.length <= 1024 && !value.includes('\\\\') && !value.startsWith('/') && !/[\\u0000-\\u001f]/.test(value) && value.split('/').every((segment) => segment && segment !== '.' && segment !== '..'); }",
    "function packageFile(value) { const target = path.resolve(root, ...value.split('/')); if (target !== root && !target.startsWith(root + path.sep)) fail('package_manifest_invalid', `导出清单路径越界: ${value}`); return target; }",
    "",
    "function runCommand(action) {",
    "  const statePath = option('--state');",
    "  if (!statePath) usage(`skill-engine.mjs run ${action} --state <file>`);",
    "  if (action === 'start') {",
    "    if (!graph.entry) fail('graph_not_executable', '当前 Skill 没有可执行入口');",
    "    if (existsSync(statePath) && !flag('--force')) fail('state_exists', '状态文件已存在；使用 --force 明确覆盖');",
    "    const variables = jsonObject(option('--variables') ?? '{}', '--variables');",
    "    const entry = node(graph.entry);",
    "    const at = new Date().toISOString();",
    "    const state = { schemaVersion: '1.0', skillId: manifest.skillId, status: entry.kind === 'end' ? 'completed' : 'running', currentNodeId: entry.id, step: 0, variables, visitedNodeIds: [entry.id], eventSeq: 0, events: [], createdAt: at, updatedAt: at };",
    "    append(state, 'engine.start', entry.id, {});",
    "    append(state, 'engine.enter', entry.id, {});",
    "    if (state.status === 'completed') append(state, 'engine.complete', entry.id, {});",
    "    saveState(statePath, state);",
    "    result(state, state.status === 'completed' ? 'done' : 'ok', state.events);",
    "    return;",
    "  }",
    "",
    "  const state = loadState(statePath);",
    "  const beforeSeq = state.eventSeq;",
    "  if (action === 'status') return result(state, state.status === 'completed' ? 'done' : 'ok', []);",
    "  if (action === 'next') {",
    "    if (state.status !== 'running') return reject(state, 'run_not_active', '运行不是 running 状态');",
    "    const target = option('--to');",
    "    if (!target) usage('skill-engine.mjs run next --state <file> --to <nodeId> [--set <json>]');",
    "    const patch = jsonObject(option('--set') ?? '{}', '--set');",
    "    const candidateVariables = { ...state.variables, ...patch };",
    "    const allowed = transitions(state.currentNodeId, candidateVariables, state);",
    "    const edge = allowed.find((item) => item.to === target);",
    "    if (!edge) {",
    "      append(state, 'engine.reject', state.currentNodeId, { requestedNodeId: target, allowedNodeIds: allowed.map((item) => item.to) });",
    "      state.updatedAt = new Date().toISOString(); saveState(statePath, state);",
    "      return reject(state, 'next_node_not_allowed', `节点 ${target} 不是当前合法出口`, target, allowed, state.events.slice(-1));",
    "    }",
    "    const targetNode = node(target);",
    "    state.variables = candidateVariables;",
    "    state.currentNodeId = targetNode.id;",
    "    state.step += 1;",
    "    state.visitedNodeIds.push(targetNode.id);",
    "    append(state, 'engine.enter', targetNode.id, { viaEdgeId: edge.edgeId });",
    "    if (targetNode.kind === 'end') { state.status = 'completed'; append(state, 'engine.complete', targetNode.id, {}); }",
    "  } else if (action === 'pause') {",
    "    if (state.status !== 'running') return reject(state, 'run_not_active', '只有 running 状态可以暂停');",
    "    state.status = 'paused'; append(state, 'engine.pause', state.currentNodeId, {});",
    "  } else if (action === 'resume') {",
    "    if (state.status !== 'paused') return reject(state, 'run_not_paused', '只有 paused 状态可以继续');",
    "    state.status = 'running'; append(state, 'engine.resume', state.currentNodeId, {});",
    "  } else if (action === 'stop') {",
    "    if (state.status !== 'running' && state.status !== 'paused') return reject(state, 'run_not_active', '只有活动运行可以停止');",
    "    state.status = 'stopped'; append(state, 'engine.stop', state.currentNodeId, {});",
    "  } else {",
    "    usage('skill-engine.mjs run <start|status|next|pause|resume|stop> --state <file>');",
    "  }",
    "  state.updatedAt = new Date().toISOString();",
    "  saveState(statePath, state);",
    "  result(state, state.status === 'completed' ? 'done' : 'ok', state.events.filter((event) => event.seq > beforeSeq));",
    "}",
    "",
    "function validateGraph() {",
    "  if (!plainObject(manifest) || typeof manifest.skillId !== 'string') fail('manifest_invalid', 'skill.json 缺少有效 skillId');",
    "  if (!plainObject(graph) || graph.schemaVersion !== '1.0') fail('graph_invalid', '仅支持图 Schema 1.0');",
    "  if (graph.skillId !== manifest.skillId) fail('graph_identity_mismatch', 'graph skillId 与 skill.json 不一致');",
    "  if (graph.capability !== 'workflow' && graph.capability !== 'content-only') fail('graph_invalid', '图 capability 无效');",
    "  if (!Array.isArray(graph.nodes) || !Array.isArray(graph.edges)) fail('graph_invalid', '图 nodes 和 edges 必须是数组');",
    `  const nodeKinds = new Set(${nodeKinds});`,
    `  const edgeKinds = new Set(${edgeKinds});`,
    "  const idPattern = /^[a-z][a-z0-9._-]{1,127}$/i; const nodeIds = new Set(); const edgeIds = new Set();",
    "  for (const item of graph.nodes) {",
    "    if (!plainObject(item) || typeof item.id !== 'string' || !idPattern.test(item.id) || nodeIds.has(item.id)) fail('graph_invalid', '节点 ID 无效或重复');",
    "    if (!nodeKinds.has(item.kind) || typeof item.title !== 'string' || !item.title.trim()) fail('graph_invalid', `节点 ${item.id} 的类型或标题无效`);",
    "    nodeIds.add(item.id);",
    "  }",
    "  for (const edge of graph.edges) {",
    "    if (!plainObject(edge) || typeof edge.id !== 'string' || !idPattern.test(edge.id) || edgeIds.has(edge.id)) fail('graph_invalid', '边 ID 无效或重复');",
    "    if (!edgeKinds.has(edge.kind) || !nodeIds.has(edge.from) || !nodeIds.has(edge.to)) fail('graph_invalid', `边 ${edge.id} 的类型或端点无效`);",
    "    if (edge.condition !== undefined) validateConditionShape(edge.condition);",
    "    edgeIds.add(edge.id);",
    "  }",
    "  if (graph.capability === 'content-only') {",
    "    if (graph.entry !== undefined || graph.nodes.some((item) => item.kind !== 'knowledge') || graph.edges.some((edge) => edge.kind !== 'knowledge')) fail('graph_not_executable', '内容型 Skill 不能声明可执行流程');",
    "    return;",
    "  }",
    "  const entry = graph.nodes.find((item) => item.id === graph.entry);",
    "  if (!entry || entry.kind !== 'start') fail('graph_invalid', '工作流入口必须是存在的 start 节点');",
    "  const reachable = new Set([entry.id]); const queue = [entry.id];",
    "  while (queue.length) { const current = queue.shift(); for (const edge of graph.edges) { if (edge.kind !== 'knowledge' && edge.from === current && !reachable.has(edge.to)) { reachable.add(edge.to); queue.push(edge.to); } } }",
    "  if (!graph.nodes.some((item) => item.kind === 'end' && reachable.has(item.id))) fail('graph_invalid', '工作流没有可从入口到达的 end 节点');",
    "}",
    "",
    "function validateConditionShape(condition, depth = 0) {",
    "  if (depth > 32 || !plainObject(condition)) fail('invalid_condition', '条件必须是深度不超过 32 的结构化对象');",
    "  if (condition.op === 'boolean') { if (typeof condition.value !== 'boolean') fail('invalid_condition', '布尔条件值无效'); return; }",
    "  if (condition.op === 'not') return validateConditionShape(condition.condition, depth + 1);",
    "  if (condition.op === 'equals' || condition.op === 'notEquals') { validateOperandShape(condition.left); validateOperandShape(condition.right); return; }",
    "  if (condition.op === 'contains') { validateOperandShape(condition.container); validateOperandShape(condition.value); return; }",
    "  if (condition.op === 'and' || condition.op === 'or') {",
    "    if (!Array.isArray(condition.conditions) || condition.conditions.length < 1 || condition.conditions.length > 100) fail('invalid_condition', '组合条件必须包含 1 到 100 个子条件');",
    "    for (const child of condition.conditions) validateConditionShape(child, depth + 1); return;",
    "  }",
    "  fail('invalid_condition', `不支持的条件操作 ${String(condition.op)}`);",
    "}",
    "",
    "function validateOperandShape(value) {",
    "  if (!plainObject(value)) fail('invalid_condition_operand', '条件操作数无效');",
    "  if (value.kind === 'literal') { const values = Array.isArray(value.value) ? value.value : [value.value]; if (!values.every((item) => item === null || ['string', 'number', 'boolean'].includes(typeof item))) fail('invalid_condition_operand', '条件字面值无效'); return; }",
    "  if (value.kind !== 'ref' || typeof value.path !== 'string' || !/^(skill|runtime)(?:\\.[A-Za-z_][A-Za-z0-9_-]*)+$/.test(value.path) || value.path.split('.').some((segment) => ['__proto__', 'prototype', 'constructor'].includes(segment))) fail('invalid_condition_operand', '条件引用必须是安全的 skill.* 或 runtime.* 路径');",
    "}",
    "",
    "function transitions(nodeId, variables, runtimeState) {",
    "  node(nodeId);",
    "  const scope = { skill: variables, runtime: { step: runtimeState?.step ?? 0, currentNodeId: nodeId, visitedNodeIds: runtimeState?.visitedNodeIds ?? [nodeId] } };",
    "  return graph.edges.filter((edge) => edge.from === nodeId && edge.kind !== 'knowledge' && evaluate(edge.condition, scope)).map((edge) => ({ edgeId: edge.id, to: edge.to, kind: edge.kind, label: edge.label ?? null }));",
    "}",
    "",
    "function evaluate(condition, variables) {",
    "  if (condition === undefined) return true;",
    "  if (!condition || typeof condition !== 'object' || Array.isArray(condition)) fail('invalid_condition', '边条件不是有效对象');",
    "  if (condition.op === 'boolean') return condition.value === true;",
    "  if (condition.op === 'not') return !evaluate(condition.condition, variables);",
    "  if (condition.op === 'and') return Array.isArray(condition.conditions) && condition.conditions.every((item) => evaluate(item, variables));",
    "  if (condition.op === 'or') return Array.isArray(condition.conditions) && condition.conditions.some((item) => evaluate(item, variables));",
    "  if (condition.op === 'equals') return sameValue(operand(condition.left, variables), operand(condition.right, variables));",
    "  if (condition.op === 'notEquals') return !sameValue(operand(condition.left, variables), operand(condition.right, variables));",
    "  if (condition.op === 'contains') {",
    "    const container = operand(condition.container, variables); const value = operand(condition.value, variables);",
    "    return typeof container === 'string' ? typeof value === 'string' && container.includes(value) : Array.isArray(container) && container.some((item) => sameValue(item, value));",
    "  }",
    "  fail('invalid_condition', `不支持的条件操作 ${String(condition.op)}`);",
    "}",
    "",
    "function operand(value, variables) {",
    "  if (!value || typeof value !== 'object' || Array.isArray(value)) fail('invalid_condition_operand', '条件操作数无效');",
    "  if (value.kind === 'literal') return value.value;",
    "  if (value.kind !== 'ref' || typeof value.path !== 'string') fail('invalid_condition_operand', '条件引用无效');",
    "  let current = variables;",
    "  for (const segment of value.path.split('.').filter(Boolean)) {",
    "    if (!current || typeof current !== 'object' || !Object.hasOwn(current, segment)) return undefined;",
    "    current = current[segment];",
    "  }",
    "  return current;",
    "}",
    "",
    "function sameValue(left, right) {",
    "  if (Object.is(left, right)) return true;",
    "  return Array.isArray(left) && Array.isArray(right) && JSON.stringify(left) === JSON.stringify(right);",
    "}",
    "",
    "function append(state, type, nodeId, data) { state.eventSeq += 1; state.events.push({ seq: state.eventSeq, at: new Date().toISOString(), actor: 'engine', type, nodeId, data }); }",
    "function node(nodeId) { const value = graph.nodes.find((item) => item.id === nodeId); if (!value) fail('node_not_found', `节点 ${nodeId} 不存在`); return value; }",
    "function option(name) { const index = process.argv.indexOf(name); if (index < 0) return undefined; const value = process.argv[index + 1]; if (!value || value.startsWith('--')) usage(`${name} 需要值`); return value; }",
    "function flag(name) { return process.argv.includes(name); }",
    "function jsonObject(value, name) { let parsed; try { parsed = JSON.parse(value); } catch { fail('invalid_json', `${name} 必须是 JSON`); } if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) fail('invalid_json_object', `${name} 必须是 JSON 对象`); return parsed; }",
    "function readJson(file, label) { try { return JSON.parse(readFileSync(file, 'utf8')); } catch (error) { fail('read_failed', `无法读取 ${label}: ${error.message}`); } }",
    "function loadState(file) { const state = readJson(path.resolve(file), '状态文件'); if (!plainObject(state) || state.schemaVersion !== '1.0' || state.skillId !== manifest.skillId || !['running', 'paused', 'completed', 'stopped'].includes(state.status) || typeof state.currentNodeId !== 'string' || !Number.isInteger(state.step) || state.step < 0 || !Number.isInteger(state.eventSeq) || state.eventSeq < 0 || !plainObject(state.variables) || !Array.isArray(state.visitedNodeIds) || !Array.isArray(state.events)) fail('state_identity_mismatch', '状态文件不属于当前 Skill 或格式不兼容'); node(state.currentNodeId); return state; }",
    "function plainObject(value) { return typeof value === 'object' && value !== null && !Array.isArray(value); }",
    "function saveState(file, state) { const target = path.resolve(file); mkdirSync(path.dirname(target), { recursive: true }); const temporary = `${target}.tmp-${process.pid}`; writeFileSync(temporary, JSON.stringify(state, null, 2) + '\\n', { mode: 0o600 }); renameSync(temporary, target); }",
    "function result(state, status, newEvents) { output({ status, state, allowedTransitions: state.status === 'running' ? transitions(state.currentNodeId, state.variables, state) : [], newEvents }); }",
    "function reject(state, code, message, requestedNodeId, allowedTransitions = state.status === 'running' ? transitions(state.currentNodeId, state.variables, state) : [], newEvents = []) { output({ status: 'rejected', state, allowedTransitions, newEvents, rejection: { code, message, ...(requestedNodeId ? { requestedNodeId } : {}) } }); }",
    "function output(value) { process.stdout.write(JSON.stringify(value, null, 2) + '\\n'); }",
    "function usage(message) { process.stderr.write(`Usage: ${message}\\n`); process.exit(2); }",
    "function fail(code, message, details) { process.stderr.write(JSON.stringify({ error: { code, message, ...(details === undefined ? {} : { details }) } }) + '\\n'); process.exit(1); }",
    ""
  ].join("\n");
}

export function genericEngineUsage(): string {
  return `# Generic Skill Engine

Requires Node.js 20 or newer. The CLI has no npm dependencies, does not access the network, and never executes files from \`scripts/\`.

## Verify

\`node engine/skill-engine.mjs verify\`

Checks every file declared by \`export-manifest.json\` against its recorded size and SHA-256 before an external Agent uses the package.

## Inspect

\`node engine/skill-engine.mjs inspect\`

\`node engine/skill-engine.mjs transitions flow.start --variables '{"approved":true}'\`

## Run

\`node engine/skill-engine.mjs run start --state ./run.json --variables '{"approved":true}'\`

\`node engine/skill-engine.mjs run next --state ./run.json --to flow.next --set '{"result":"ok"}'\`

\`node engine/skill-engine.mjs run pause --state ./run.json\`

\`node engine/skill-engine.mjs run resume --state ./run.json\`

\`node engine/skill-engine.mjs run stop --state ./run.json\`

\`node engine/skill-engine.mjs run status --state ./run.json\`

Every command writes one JSON result to stdout. When \`next\` rejects an undeclared or condition-disabled target, it keeps the current node, step, and variables unchanged while persisting an \`engine.reject\` Trace event. The state file contains variables and engine Trace; keep it outside the Skill directory when the package must remain immutable.
`;
}
